services:
  - type: web
    name: deadline-tracker-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: deadline-tracker-db
          property: connectionString
    healthCheckPath: /api/health

databases:
  - name: deadline-tracker-db
    plan: free
