services:
  - type: web
    name: deadline-tracker-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres:n+rG2Hb+E4ME7Sf@db.fqmahzjzhhywyjxriqvx.supabase.co:5432/postgres
    healthCheckPath: /api/health
